### ISSUE TITLE
Issue with OtherPublicHoliday fails conversion

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#54]
@linusnorton 
Recently I found a new issue with "OtherPublicHoliday" field in the latest Traveline .xml.
Looks like the Jubilee bank holiday will be celebrated across the UK and some operators added it as "OtherPublicHoliday" in incorrect way. 

There are several files with the similar issue. One of them:
[W_SC_SSWL_130_2_A.zip](https://github.com/planarnetwork/transxchange2gtfs/files/8504155/W_SC_SSWL_130_2_A.zip)

The issue is in this part of TransXChangeStream file:
```
        if ((_d = (_c = profile.BankHolidayOperation) === null || _c === void 0 ? void 0 : _c[0].DaysOfNonOperation) === null || _d === void 0 ? void 0 : _d[0]) {
            result.BankHolidayOperation.DaysOfNonOperation = this.getHolidays(profile.BankHolidayOperation[0].DaysOfNonOperation[0]);
            if (profile.BankHolidayOperation[0].DaysOfNonOperation[0].OtherPublicHoliday) {
                const nonOperationDates = profile.BankHolidayOperation[0].DaysOfNonOperation[0].OtherPublicHoliday
                    .map((d) => this.getHolidayDate(d.Date[0]));
                result.SpecialDaysOperation.DaysOfNonOperation.push(...nonOperationDates);
            }
```

The conversion exits with an exception stack trace (line numbers may differ from the original):

```
Processing W_SC_SSWL_130_2_A.xml
(node:842054) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at /home/ubuntu/converters/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:195:59
    at Array.map (<anonymous>)
    at TransXChangeStream.getOperatingProfile (/home/ubuntu/converters/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:195:22)
    at TransXChangeStream.getServices (/home/ubuntu/converters/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:128:24)
    at Array.reduce (<anonymous>)
    at TransXChangeStream._transform (/home/ubuntu/converters/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:33:49)
    at TransXChangeStream.Transform._read (internal/streams/transform.js:205:10)
    at TransXChangeStream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at TransXChangeStream.Writable.write (internal/streams/writable.js:303:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:842054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:842054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by linusnorton** [comment]
I've released a fix for this in version 1.10.4

**Comment by tafflin** [comment]
Hi @linusnorton ,
looks like the issue still persist for some of the files. For example, in W.zip by Traveline there are 4 files that have errors like
```
Processing W_SC_SSWL_124_1.xml
TypeError: Cannot read properties of undefined (reading '0')
    at /usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:177:59
    at Array.map (<anonymous>)
    at TransXChangeStream.getOperatingProfile (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:177:22)
    at TransXChangeStream.getServices (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:120:24)
    at Array.reduce (<anonymous>)
    at TransXChangeStream._transform (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:34:53)
    at TransXChangeStream.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at TransXChangeStream.Writable.write (node:internal/streams/writable:334:10)
```
attached all 4 of them
[not-converted.zip](https://github.com/planarnetwork/transxchange2gtfs/files/8629236/not-converted.zip)
